from typing import Literal


STATE_REVIEWING = 'reviewing'
STATE_NEGOTIATING = 'negotiating'
STATE_READY_FOR_DELIVERY = 'ready_for_delivery'
STATE_DELIVERED = 'delivered'
STATE_CANCELED = 'canceled'

STORE_STATE_VALID = Literal[
    STATE_REVIEWING,
    STATE_NEGOTIATING,
    STATE_READY_FOR_DELIVERY,
    STATE_DELIVERED,
    STATE_CANCELED,
]
DEFAULT_STORE_STATE: STORE_STATE_VALID = STATE_REVIEWING

STORE_STATE_VALID_CHOICES = [
    (STATE_REVIEWING, 'Revisando'),
    (STATE_NEGOTIATING, 'Negociando'),
    (STATE_READY_FOR_DELIVERY, 'Listo para entrega'),
    (STATE_DELIVERED, 'Entregado'),
    (STATE_CANCELED, 'Cancelado'),
]