# Part of Odoo. See LICENSE file for full copyright and licensing details.

from .bodies import (
    AddressFull,
    AddressPatch,
    OrderCreateBody,
    OrderLineIn,
    ProfilePatchBody,
    ProfilePutBody,
    PushTokenBody,
    PushTopicsPatchBody,
    RegisterBody,
)
from .errors import pydantic_errors_to_api_body
from .query import OrdersListQuery, ProductsListQuery
from .responses import (
    CategoriesListResponse,
    ConfigurationErrorResponse,
    GeneralSettingsResponse,
    InsufficientStockErrorResponse,
    MessageErrorResponse,
    OrderCancelResponse,
    OrderCreatedResponse,
    OrdersPageResponse,
    ProductDetailResponse,
    ProductsPageResponse,
    ProfileResponse,
    PushTopicsOkResponse,
    RegisterOkResponse,
    SaleOrderDetailResponse,
    SimpleErrorResponse,
    StatusResponse,
    UnauthorizedErrorResponse,
    ValidationErrorResponse,
)

__all__ = [
    'AddressFull',
    'AddressPatch',
    'OrderCreateBody',
    'OrderLineIn',
    'OrdersListQuery',
    'ProductsListQuery',
    'ProfilePatchBody',
    'ProfilePutBody',
    'PushTokenBody',
    'PushTopicsPatchBody',
    'RegisterBody',
    'RegisterOkResponse',
    'SaleOrderDetailResponse',
    'SimpleErrorResponse',
    'StatusResponse',
    'UnauthorizedErrorResponse',
    'ValidationErrorResponse',
    'CategoriesListResponse',
    'ConfigurationErrorResponse',
    'GeneralSettingsResponse',
    'InsufficientStockErrorResponse',
    'MessageErrorResponse',
    'OrderCancelResponse',
    'OrderCreatedResponse',
    'OrdersPageResponse',
    'ProductDetailResponse',
    'ProductsPageResponse',
    'ProfileResponse',
    'PushTopicsOkResponse',
    'pydantic_errors_to_api_body',
]
